/** Same canon/chapter-count data as the backend's BIBLE_BOOKS table in
 * swordService.js (kept separate rather than shared, since one is
 * Node/CommonJS-adjacent backend code and this is bundled frontend code)
 * — with human-readable names added, since this one drives a picker UI
 * rather than a chapter-by-chapter scan. */
export const BIBLE_BOOKS = [
  { osis: 'Gen', name: 'Genesis', chapters: 50, testament: 'OT' },
  { osis: 'Exod', name: 'Exodus', chapters: 40, testament: 'OT' },
  { osis: 'Lev', name: 'Leviticus', chapters: 27, testament: 'OT' },
  { osis: 'Num', name: 'Numbers', chapters: 36, testament: 'OT' },
  { osis: 'Deut', name: 'Deuteronomy', chapters: 34, testament: 'OT' },
  { osis: 'Josh', name: 'Joshua', chapters: 24, testament: 'OT' },
  { osis: 'Judg', name: 'Judges', chapters: 21, testament: 'OT' },
  { osis: 'Ruth', name: 'Ruth', chapters: 4, testament: 'OT' },
  { osis: '1Sam', name: '1 Samuel', chapters: 31, testament: 'OT' },
  { osis: '2Sam', name: '2 Samuel', chapters: 24, testament: 'OT' },
  { osis: '1Kgs', name: '1 Kings', chapters: 22, testament: 'OT' },
  { osis: '2Kgs', name: '2 Kings', chapters: 25, testament: 'OT' },
  { osis: '1Chr', name: '1 Chronicles', chapters: 29, testament: 'OT' },
  { osis: '2Chr', name: '2 Chronicles', chapters: 36, testament: 'OT' },
  { osis: 'Ezra', name: 'Ezra', chapters: 10, testament: 'OT' },
  { osis: 'Neh', name: 'Nehemiah', chapters: 13, testament: 'OT' },
  { osis: 'Esth', name: 'Esther', chapters: 10, testament: 'OT' },
  { osis: 'Job', name: 'Job', chapters: 42, testament: 'OT' },
  { osis: 'Ps', name: 'Psalms', chapters: 150, testament: 'OT' },
  { osis: 'Prov', name: 'Proverbs', chapters: 31, testament: 'OT' },
  { osis: 'Eccl', name: 'Ecclesiastes', chapters: 12, testament: 'OT' },
  { osis: 'Song', name: 'Song of Solomon', chapters: 8, testament: 'OT' },
  { osis: 'Isa', name: 'Isaiah', chapters: 66, testament: 'OT' },
  { osis: 'Jer', name: 'Jeremiah', chapters: 52, testament: 'OT' },
  { osis: 'Lam', name: 'Lamentations', chapters: 5, testament: 'OT' },
  { osis: 'Ezek', name: 'Ezekiel', chapters: 48, testament: 'OT' },
  { osis: 'Dan', name: 'Daniel', chapters: 12, testament: 'OT' },
  { osis: 'Hos', name: 'Hosea', chapters: 14, testament: 'OT' },
  { osis: 'Joel', name: 'Joel', chapters: 3, testament: 'OT' },
  { osis: 'Amos', name: 'Amos', chapters: 9, testament: 'OT' },
  { osis: 'Obad', name: 'Obadiah', chapters: 1, testament: 'OT' },
  { osis: 'Jonah', name: 'Jonah', chapters: 4, testament: 'OT' },
  { osis: 'Mic', name: 'Micah', chapters: 7, testament: 'OT' },
  { osis: 'Nah', name: 'Nahum', chapters: 3, testament: 'OT' },
  { osis: 'Hab', name: 'Habakkuk', chapters: 3, testament: 'OT' },
  { osis: 'Zeph', name: 'Zephaniah', chapters: 3, testament: 'OT' },
  { osis: 'Hag', name: 'Haggai', chapters: 2, testament: 'OT' },
  { osis: 'Zech', name: 'Zechariah', chapters: 14, testament: 'OT' },
  { osis: 'Mal', name: 'Malachi', chapters: 4, testament: 'OT' },

  { osis: 'Matt', name: 'Matthew', chapters: 28, testament: 'NT' },
  { osis: 'Mark', name: 'Mark', chapters: 16, testament: 'NT' },
  { osis: 'Luke', name: 'Luke', chapters: 24, testament: 'NT' },
  { osis: 'John', name: 'John', chapters: 21, testament: 'NT' },
  { osis: 'Acts', name: 'Acts', chapters: 28, testament: 'NT' },
  { osis: 'Rom', name: 'Romans', chapters: 16, testament: 'NT' },
  { osis: '1Cor', name: '1 Corinthians', chapters: 16, testament: 'NT' },
  { osis: '2Cor', name: '2 Corinthians', chapters: 13, testament: 'NT' },
  { osis: 'Gal', name: 'Galatians', chapters: 6, testament: 'NT' },
  { osis: 'Eph', name: 'Ephesians', chapters: 6, testament: 'NT' },
  { osis: 'Phil', name: 'Philippians', chapters: 4, testament: 'NT' },
  { osis: 'Col', name: 'Colossians', chapters: 4, testament: 'NT' },
  { osis: '1Thess', name: '1 Thessalonians', chapters: 5, testament: 'NT' },
  { osis: '2Thess', name: '2 Thessalonians', chapters: 3, testament: 'NT' },
  { osis: '1Tim', name: '1 Timothy', chapters: 6, testament: 'NT' },
  { osis: '2Tim', name: '2 Timothy', chapters: 4, testament: 'NT' },
  { osis: 'Titus', name: 'Titus', chapters: 3, testament: 'NT' },
  { osis: 'Phlm', name: 'Philemon', chapters: 1, testament: 'NT' },
  { osis: 'Heb', name: 'Hebrews', chapters: 13, testament: 'NT' },
  { osis: 'Jas', name: 'James', chapters: 5, testament: 'NT' },
  { osis: '1Pet', name: '1 Peter', chapters: 5, testament: 'NT' },
  { osis: '2Pet', name: '2 Peter', chapters: 3, testament: 'NT' },
  { osis: '1John', name: '1 John', chapters: 5, testament: 'NT' },
  { osis: '2John', name: '2 John', chapters: 1, testament: 'NT' },
  { osis: '3John', name: '3 John', chapters: 1, testament: 'NT' },
  { osis: 'Jude', name: 'Jude', chapters: 1, testament: 'NT' },
  { osis: 'Rev', name: 'Revelation', chapters: 22, testament: 'NT' },
];